apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: csi-snapshot-webhook-pdb
  namespace: ${NAMESPACE}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: csi-snapshot-webhook
